#!/bin/bash

set -e

CERT_NAME=
DOMAINS=()
STAGING=
WILDCARD=
FORCE=

while test -n "$1"; do
    case "$1" in
	--cert-name)
        CERT_NAME=$2
	    shift
	    shift
	    ;;
	--domain)
        DOMAINS+=($2)
	    shift
	    shift
	    ;;
	--wildcard)
	    WILDCARD=1
	    shift
	    ;;
	--staging)
	    STAGING=1
	    shift
	    ;;
	--force)
	    FORCE=--force
	    shift
	    ;;
	*)
	    echo "Unknown argument: $1"
	    exit 1
	    ;;
  esac
done

if [ -z "$CERT_NAME" ] ; then
    echo "==> Please provide a --cert-name argument."
    exit 1
fi

if [ ${#DOMAINS[@]} -eq 0 ] ; then
    echo "==> Please provide a --domain foo.tld argument."
    exit 1
fi

if [ ${#DOMAINS[@]} -gt 1 ] && [ "$WILDCARD" ] ; then
    echo "==> Please only specify one --domain foo.tld argument for a wildcard certificate."
    exit 1
fi

if [ "$STAGING" ] ; then
    SERVER="https://acme-staging-v02.api.letsencrypt.org/directory"
else
    SERVER="https://acme-v02.api.letsencrypt.org/directory"
fi

DOMAIN=${DOMAINS[0]}
DOMAIN_ALIAS=""
if [ "$WILDCARD" ] ; then
    export NSUPDATE_SERVER="ns0.ukcod.org.uk"
    export NSUPDATE_KEY="/data/letsencrypt/etc/acme.key"

    DOMAIN_PARAMS=(-d "${DOMAIN}" -d "*.${DOMAIN}")
    MODE="--dns dns_nsupdate"

    if [ "$DOMAIN" == "whatdotheyknow.com" ]; then
        source /data/letsencrypt/etc/cf_token.sh
        MODE="--dns dns_cf"
    else
        DOMAIN_ALIAS="--domain-alias ${DOMAIN}.acme.mysociety.org"
    fi
else
    DOMAIN_PARAMS=()
    for D in "${DOMAINS[@]}" ; do
        DOMAIN_PARAMS+=(-d "${D}")
    done

    MODE="--webroot /data/letsencrypt/webroot/"
fi

echo "==> Attempting to issue cert for $DOMAIN"
cd /data/letsencrypt/acme.sh
source ./acme.sh.env
./acme.sh --issue "${DOMAIN_PARAMS[@]}" \
          $MODE \
          $DOMAIN_ALIAS \
          --server $SERVER \
          --keylength 4096 \
          --pre-hook "/data/vhost/acme-challenge.mysociety.org/ssl-scripts/acme-pre-hook" \
          $FORCE

if [ "$?" -ne "0" ] ; then
   echo "==> There was a problem issuing the certificate for ${DOMAIN}."
   exit 1
fi

echo "==> Attempting to install certificate for ${DOMAIN}."
PUPPET_PATH=/data/puppet/site/profiles/files/certificates/etc/ssl/mysociety
if [ "$STAGING" == "" ] ; then
    CRT_PATH=${PUPPET_PATH}/certs
    KEY_PATH=${PUPPET_PATH}/keys
    CMD="/data/vhost/acme-challenge.mysociety.org/ssl-scripts/acme-reloadcmd ${DOMAIN}"
else
    CRT_PATH=/tmp
    KEY_PATH=/tmp
    CMD="/bin/true"
fi

./acme.sh --install-cert -d ${DOMAIN} \
         --fullchain-file "${CRT_PATH}/${CERT_NAME}.crt" \
         --ca-file "${CRT_PATH}/${CERT_NAME}.ca.crt" \
         --key-file "${KEY_PATH}/${CERT_NAME}.key" \
         --reloadcmd "${CMD}" \
         --force

# Ensure public read perms as, without this, the puppet
# repo shows to other users as having local changes
# which then breaks some flows.
chmod 644 "${KEY_PATH}/${CERT_NAME}.key"
